config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root 'events#index'

  resources :organisers do
    resources :events
  end
  resources :events, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organiser
  validates :title, presence: true
  validates :location, presence: true
  validates :special, presence: true
  validates :dresscode, presence: true
  validates :recurrence, presence: true
  serialize :recurrence, coder: Montrose::Recurrence
end

app/models/organiser.rb
class Organiser < ApplicationRecord
  has_many :events
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_event, only: %i[show edit update destroy]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @organiser = Organiser.find(params[:organiser_id])
  end

  def create
    on = params[:event][:recurrence][:on].shift.to_sym
    @event = Event.new(event_params)
    @event.organiser = Organiser.find(params[:organiser_id])
    if @event.save!
      redirect_to [@organiser, @event], notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @organiser_id = @event.organiser
    @event.update(event_params)
    redirect_to organiser_events_path(@organiser_id), notice: 'Event was successfully created.'
  end

  def destroy
    @organiser_id = @event.organiser
    @event.destroy
    redirect_to organiser_events_path(@organiser_id)
  end

  private

  def event_params
    params.require(:event).permit(
      :title,
      :location,
      :line_up,
      :style,
      :special,
      :dresscode,
      recurrence: [:every, :interval, :total, :at, :starts, :until, on: []]
    )
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
end

app/controllers/organisers_controller.rb
class OrganisersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_organiser, only: %i[show edit update destroy]
  def index
    @organisers = Organiser.all
  end

  def new
    @organiser = Organiser.new
  end

  def create
    @organiser = Organiser.new(organiser_params)
    if @organiser.save
      redirect_to organiser_path(@organiser)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @organiser.update(organiser_params)
    redirect_to organiser_path(@organiser)
  end

  def destroy
    @organiser.destroy
    redirect_to organisers_path, status: :see_other
  end

  private

  def organiser_params
    params.require(:organiser).permit(:name, :url, :facebook, :instagram, :soundcloud)
  end

  def set_organiser
    @organiser = Organiser.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organisers_helper.rb
module OrganisersHelper
end

app/views/application/home.html.erb
<h1>Home page</h1>

app/views/events/_form.html.erb
<%= simple_form_for([@organiser, @event]) do |f| %>
  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.simple_fields_for :recurrence do |ff| %>
    <%= ff.input :every, collection: ['day', 'week', 'month', 'year'], as: :select %>
    <%= ff.input :interval, as: :integer %>
    <%# <%= ff.input :total, as: :integer %>
    <%# <%= ff.collection_check_boxes :on, [[:monday, 'Monday'], [:tuesday, 'Tuesday']], :first, :last %>
    <%= ff.input :on, collection: Date::DAYNAMES, as: :check_boxes %>
    <%= ff.input :at, as: :time, html5: true %>
    <%= ff.input :starts, as: :date, html5: true %>
    <%= ff.input :until, as: :date, html5: true %>
  <% end %>
  <%= f.input :line_up %>
  <%= f.input :style %>
  <%= f.input :special %>
  <%= f.input :dresscode %>
  <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<%= render "form", event: @event, organiser: @event.organiser %>

app/views/events/index.html.erb
<div>
  <% @events.each do |event| %>
    <p><%= link_to event.title, organiser_event_path(event.organiser, event) %></p>
  <% end %>
</div>

app/views/events/new.html.erb
<%= render "form", organiser: @organiser, event: @event %>

app/views/events/show.html.erb
<div class="border-2">
  <h1 class="text-2xl font-bold text-blue-600"><%= @event.title %></h1>
  <p class="mb-4 bg-[#bada55]"><%= @event.location %></p>
  <p class="text-xl"><%= @event.recurrence.to_hash %></p>
  <h2>Occurrences:</h2>
  <ul>
    <li>Every: <%= @event.recurrence.to_hash[:every] %> </li>
    <li>Every: <%= @event.recurrence.to_hash[:every] %> </li>
  </ul>
  <p><%= @event.line_up %></p>
  <p><%= @event.style %></p>
  <p><%= @event.special %></p>
  <p><%= @event.dresscode %></p>
</div>
<% if user_signed_in? %>
  <%= link_to "Edit",
      edit_organiser_event_path(@event.organiser, @event)
  %>
  <%= link_to "Delete",
      organiser_event_path(@event),
      data: {turbo_method: :delete, turbo_comfirm: "Are you sure?"}
  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kitkatclub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/organisers/_form.html.erb
<%= simple_form_for(@organiser) do |f| %>
<%= f.input :name %>
<%= f.input :url %>
<%= f.input :instagram %>
<%= f.input :facebook %>
<%= f.input :soundcloud %>
<%= f.button :submit %>
<% end %>

app/views/organisers/edit.html.erb
<%= render "form", organiser: @organiser %>

app/views/organisers/index.html.erb
<div>
  <% @organisers.each do |organiser| %>
    <p><%= link_to organiser.name, organiser_path(organiser) %></p>
  <% end %>
</div>

app/views/organisers/new.html.erb
<%= render "form", organiser: @organiser %>

app/views/organisers/show.html.erb
<div class="border-2">
  <h1 class="text-2xl font-bold text-blue-600"><%= @organiser.name %></h1>
  <p class="mb-4 bg-[#bada55]"><%= @organiser.url %></p>
  <p class="text-xl"><%= @organiser.instagram %></p>
  <p><%= @organiser.facebook %></p>
  <p><%= @organiser.soundcloud %></p>
</div>
<% if user_signed_in? %>
  <%= link_to "Edit",
    edit_organiser_path(@organiser)
  %>
  <%= link_to "Delete",
      organiser_path(@organiser),
      data: {turbo_method: :delete, turbo_comfirm: "Are you sure?"}
  %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
    <%= notice %>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-blue-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

<% if alert %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <%= alert %>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
    </span>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <%= link_to "KitKatClub", events_path(@event), class: "self-center text-2xl font-semibold whitespace-nowrap dark:text-white" %>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% if user_signed_in? %>
          <li>
            <a href="#" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" aria-current="page">Home</a>
          </li>
          <li>
            <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
          </li>
          <li>
            <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Services</a>
          </li>
          <li>
            <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Pricing</a>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
            <%# <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a> %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>